image: alpine

before_script:
- apk update
- apk add doxygen

test:
  script:
  - doxygen doxygen/Doxyfile
  except:
  - master
  
pages:
  script:
  - doxygen doxygen/Doxyfile
  - mv doxygen/doc/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
